[project]
name = "surface_chat"
description = "Serving packages for ML models"
version = "0.1.0"
authors = [
    {name = "Keith Stevens"},
]
requires-python = ">=3.9"
classifiers = [
    "Framework :: FastChat",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "pydantic",
    "tqdm"
    "bitsandbytes",
    "fschat[model_worker]",
    "protobuf",
    "scipy",
    "transformers",
    "vllm",
]

[project.optional-dependencies]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
